services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - coolify
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=3000
networks:
  coolify:
    external: true